<?php
/**
 * @file
 * Module to support custom, re-usable components for the site
 */

require_once('classes/simple_data_table/SimpleDataTableColumnViewConfig.php');
require_once('classes/simple_data_table/SimpleDataTableModel.php');
require_once('classes/simple_data_table/SimpleDataTableViewConfig.php');
require_once('classes/simple_data_table/SimpleDataTableViewModel.php');
require_once('includes/component_controller.inc');
module_load_include('php', 'mockup_utilities', 'MockData');

/**
 * Implements hook_menu()
 */

function component_controller_menu() {

    $items['simple_data_table'] = array
    (
        'title' => 'Simple Data Table Component',
        'page callback' => 'component_controller',
        'page arguments' => array('simple_data_table'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['simple_data_table/export'] = array(
        'title' => 'Export CSV',
        'page callback' => '_component_controller_simple_data_table_export',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['mwbe_spending_summary_chart_data'] = array
    (
        'title' => 'M/WBE Spending Summary Chart Data',
        'page callback' => '_component_controller_mwbe_spending_summary_chart_data',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['top_navigation_menu'] = array
    (
        'title' => 'Top Navigation Menu',
        'page callback' => 'component_controller',
        'page arguments' => array('top_navigation_menu'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['footer'] = array
    (
        'title' => 'Footer',
        'page callback' => 'component_controller',
        'page arguments' => array('footer'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


/*
 * Implementation of hook_theme().
 */
function component_controller_theme($viewModel){
    return array(
        'simple_data_table' => array(
            'template' => 'templates/simple-data-table',
            'arguments' => array('viewModel' => $viewModel),
        ),
        'top_navigation_menu' => array(
            'template' => 'templates/top-navigation-menu',
            'arguments' => array('viewModel' => $viewModel),
        ),
        'footer' => array(
            'template' => 'templates/footer',
            'arguments' => array('viewModel' => $viewModel),
        ),
        'bar_chart' => array(
            'template' => 'templates/bar-chart',
            'arguments' => array('viewModel' => $viewModel),
        )
    );
}

function component_controller($template){
    $viewModel = null;
    switch($template) {
        case "spending_landing":
            return theme($template,array('viewModel'=>$viewModel));
            break;
        default:
            return theme($template,array());
            break;
    }
}
