<?php
/**
 * @file
 * Module to support custom pages for the site
 */

require_once('includes/page_controller.inc');
module_load_include('php', 'mockup_utilities', 'MockData');

/**
 * Implements hook_menu()
 */

function page_controller_menu() {

    $items['home'] = array
    (
        'title' => 'Home',
        'page callback' => 'page_controller',
        'page arguments' => array('home'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['spending_landing'] = array
    (
        'title' => 'Spending Landing Page',
        'page callback' => 'page_controller',
        'page arguments' => array('spending_landing'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


/**
 * Implements hook_theme()
 */
function page_controller_theme($viewModel) {

    return array(
        'home' => array(
            'template' => 'templates/home-page',
            'render element' => 'page',
            'arguments' => array(),
        ),
        'spending_landing' => array(
            'template' => 'templates/spending-landing-page',
            'arguments' => array('viewModel' => $viewModel),
        )
    );
}

function page_controller($template){
    $viewModel = null;
    switch($template) {
        case "spending_landing":
            return theme($template,array('viewModel'=>$viewModel));
            break;
        default:
            return theme($template,array());
            break;
    }
}

